project_name: slsa-provenance

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0
  - DOCKER_CLI_EXPERIMENTAL=enabled

checksum:
  name_template: 'checksums.txt'

builds:
  - id: binary
    dir: cmd/slsa-provenance
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 8
    ldflags:
      - "{{ .Env.LDFLAGS }}"

archives:
  - id: archive
    format: tar.gz
    replacements:
      darwin: macOS
    files:
      - LICENSE*
      - README*
      - cosign.pub
      - dist/*.sig
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - goos: linux
    goarch: amd64
    use: buildx
    image_templates:
      - "ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}-amd64"
      - "philipssoftware/{{ .ProjectName }}:v{{ .Version }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.vendor=Koninklijke Philips N.V."
    extra_files:
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - "cmd"
      - "lib"
  - goos: linux
    goarch: arm64
    use: buildx
    image_templates:
      - "ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}-arm64v8"
      - "philipssoftware/{{ .ProjectName }}:v{{ .Version }}-arm64v8"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.vendor=Koninklijke Philips N.V."
    extra_files:
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - "cmd"
      - "lib"

docker_manifests:
  - name_template: 'ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}'
    image_templates:
      - 'ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}-amd64'
      - 'ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}-arm64v8'
  - name_template: 'ghcr.io/philips-labs/{{ .ProjectName }}:{{ .FullCommit }}'
    image_templates:
      - 'ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}-amd64'
      - 'ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Version }}-arm64v8'
  - name_template: 'philipssoftware/{{ .ProjectName }}:{{ .FullCommit }}'
    image_templates:
      - 'philipssoftware/{{ .ProjectName }}:v{{ .Version }}-amd64'
      - 'philipssoftware/{{ .ProjectName }}:v{{ .Version }}-arm64v8'
  - name_template: 'philipssoftware/{{ .ProjectName }}:v{{ .Version }}'
    image_templates:
      - 'philipssoftware/{{ .ProjectName }}:v{{ .Version }}-amd64'
      - 'philipssoftware/{{ .ProjectName }}:v{{ .Version }}-arm64v8'

signs:
  - id: checksums
    cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - --key
      - cosign.key
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
  - id: binaries
    cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    output: true
    artifacts: binary
    args:
      - sign-blob
      - --key
      - cosign.key
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
  - id: archives
    cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    output: true
    artifacts: archive
    args:
      - sign-blob
      - --key
      - cosign.key
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - 'sign'
      - --key
      - cosign.key
      - '${artifact}'

snapshot:
  name_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  draft: true
  prerelease: auto
  extra_files:
    - glob: "./cosign.pub"
  footer: |
    **Full Changelog**: https://github.com/philips-labs/slsa-provenance-action/compare/{{ .PreviousTag }}...{{ .Tag }}
