name: 'SLSA Build Provenance Action'
description: 'An action to generate SLSA build provenance for an artifact'
branding:
  icon: lock
  color: purple
inputs:
  command:
    description: 'The command to use (available options: generate)'
    required: false
    default: 'generate'
  subcommand:
    description: 'The subcommand to use when generating provenance'
    required: false
    default: 'files'
  github_context:
    description: 'internal (do not set): the "github" context object in json'
    required: true
    default: ${{ toJSON(github) }}
  runner_context:
    description: 'internal (do not set): the "runner" context object in json'
    required: true
    default: ${{ toJSON(runner) }}
  arguments:
    description: 'commandline options for the given subcommand'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/philips-labs/slsa-provenance:v0.4.0'
  args:
    - '${{ inputs.command }}'
    - '${{ inputs.subcommand }}'
    - "--github-context"
    - '${{ inputs.github_context }}'
    - "--runner-context"
    - '${{ inputs.runner_context }}'
    - ${{ inputs.arguments }}
