name: 'SLSA Build Provenance Action'
description: 'An action to generate SLSA build provenance for an artifact'
branding:
  icon: lock
  color: purple
inputs:
  command:
    description: 'The command to use (available options: generate)'
    required: false
    default: 'generate'
  subcommand:
    description: 'The subcommand to use when generating provenance'
    required: false
    default: 'files'
  github_context:
    description: 'internal (do not set): the "github" context object in json'
    required: true
    default: ${{ toJSON(github) }}
  runner_context:
    description: 'internal (do not set): the "runner" context object in json'
    required: true
    default: ${{ toJSON(runner) }}
  arguments:
    description: 'commandline options for the given subcommand'
    required: true
runs:
  using: 'composite'
  steps:
    - name: compose arguments
      id: compose-args
      shell: bash
      run: |
        encoded_github="$(echo '${{ inputs.github_context }}' | base64)"
        encoded_runner="$(echo '${{ inputs.runner_context }}' | base64)"

        args=('${{ inputs.command }}')
        args+=('${{ inputs.subcommand }}')
        args+=('--github-context')
        args+=("${encoded_github}")
        args+=('--runner-context')
        args+=("${encoded_runner}")
        args+=('${{ inputs.arguments }}')

        echo "::set-output name=provenance_args::$(echo "[$(printf "\"%s\"," ${args[*]})]" | sed 's/,]$/]/')"
    - uses: 'docker://ghcr.io/philips-labs/slsa-provenance:v0.4.0'
      with:
        args: ${{ fromJSON(steps.compose-args.outputs.provenance_args) }}
