name: 'SLSA Build Provenance Action'
description: 'An action to generate SLSA build provenance for an artifact'
branding:
  icon: lock
  color: purple
inputs:
  command:
    description: 'The command to use (available options: generate)'
    required: false
    default: 'generate'
  subcommand:
    description: 'The subcommand to use when generating provenance'
    required: false
    default: 'files'
  github_context:
    description: 'internal (do not set): the "github" context object in json'
    required: true
    default: ${{ toJSON(github) }}
  runner_context:
    description: 'internal (do not set): the "runner" context object in json'
    required: true
    default: ${{ toJSON(runner) }}
  arguments:
    description: 'commandline options for the given subcommand'
    required: true
runs:
  using: 'composite'
  steps:
    - name: compose arguments
      id: compose-args
      shell: bash
      run: |
        encoded_github="$( echo ${GITHUB_CONTEXT} | base64 -w 0)"
        encoded_runner="$( echo ${RUNNER_CONTEXT} | base64 -w 0)"

        args=(${{ inputs.command }})
        args+=(${{ inputs.subcommand }})
        args+=(--github-context)
        args+=("${encoded_github}")
        args+=(--runner-context)
        args+=("${encoded_runner}")
        args+=(${{ inputs.arguments }})

        echo "::set-output name=provenance_args::${args[@]}"
      env:
        GITHUB_CONTEXT: ${{ inputs.github_context }}
        RUNNER_CONTEXT: ${{ inputs.runner_context }}
    - name: Debug arguments
      shell: bash
      run: |
        echo Running slsa-provenance with following arguments
        echo ${{ steps.compose-args.outputs.provenance_args }}
    - uses: 'docker://ghcr.io/philips-labs/slsa-provenance:v0.6.2-draft'
      with:
        args: ${{ steps.compose-args.outputs.provenance_args }}
