# Workflow to keep action docs up to date

name: 'Action docs'
on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: npalm/action-docs-action@v1.1.0
        with:
          tocLevel: 3
          actionFile: action.yaml

      - name: Update readme in the repository
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: ":memo: Update Readme"
          file_pattern: README.md
