name: Create a provenance

on:
  workflow_dispatch:
    inputs:
      ingredient_input:
        description: 'Ingredient to input in the artifact text file'
        required: false
      car_input:
        description: 'Car to input in the artifact text file'
        required: false

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-20.04
    steps:
      # traditionally you would build your code here and generate an artifact
      - name: Create first artifact
        run:  echo "onion, tomato, jalapeno, cilantro, lime, salt" > salsa.txt

      - name: Create second artifact
        run:  echo "audi, tesla, bmw" > cars.txt

      - name: Input workflow ingredient
        if:  ${{ github.event.inputs.ingredient_input != '' }}
        run: |
          echo ", ${{github.event.inputs.ingredient_input}}" >> salsa.txt

      - name: Input workflow cars
        if:  ${{ github.event.inputs.car_input != '' }}
        run: |
          echo ", ${{github.event.inputs.car_input}}" >> cars.txt

      - name: Upload artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # ratchet:actions/upload-artifact@v4.3.0
        with:
          path: '*.txt'

  generate-provenance:
    needs: build
    name: Generate build provenance
    runs-on: ubuntu-20.04
    steps:
      # checkout only required to run local action (defined in this repo)
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4.1.1
      - name: Download build artifact
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # ratchet:actions/download-artifact@v4.1.0
      - name: Generate some extra materials (this usually happens as part of the build process)
        run: |
          echo '[{"uri": "pkg:deb/debian/stunnel4@5.50-3?arch=amd64", "digest": {"sha256": "e1731ae217fcbc64d4c00d707dcead45c828c5f762bcf8cc56d87de511e096fa"}}]' > extra-materials.json

      - name: Generate provenance
        # use action in the root directory
        uses: ./
        with:
          artifact_path: artifact/
          extra_materials: extra-materials.json

      - name: Upload provenance
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # ratchet:actions/upload-artifact@v4.3.0
        with:
          path: provenance.json
