name: Create a provenance

on:
  workflow_dispatch:
    inputs:
      ingredient_input:
        description: 'Ingredient to input in the artifact text file'     
        required: false
      car_input:
        description: 'Car to input in the artifact text file'     
        required: false

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      # traditionally you would build your code here and generate an artifact
      - name: Create first artifact
        run:  echo "onion, tomato, jalapeno, cilantro, lime, salt" > salsa.txt

      - name: Create second artifact
        run:  echo "audi, tesla, bmw" > cars.txt

      - name: Input workflow ingredient
        if:  ${{ github.event.inputs.ingredient_input != '' }}
        run: |
          echo ", ${{github.event.inputs.ingredient_input}}" >> salsa.txt

      - name: Input workflow cars
        if:  ${{ github.event.inputs.car_input != '' }}
        run: |
          echo ", ${{github.event.inputs.car_input}}" >> cars.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: '*.txt'

  generate-provenance:
    needs: build
    name: Generate build provenance
    runs-on: ubuntu-latest
    steps:
      # checkout only required to run local action (defined in this repo)
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2

      - name: Generate provenance
        # use action in the root directory
        uses: ./
        with:
          artifact_path: artifact/

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          path: build.provenance
