name: Integration test file provenance

on:
  push:
  pull_request:
    types: [ opened, reopened ]
  workflow_dispatch:

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-20.04
    steps:
      # traditionally you would build your code here and generate an artifact
      - name: Create first artifact
        run:  echo "onion, tomato, jalapeno, cilantro, lime, salt" > salsa.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: slsa
          path: '*.txt'

  generate-provenance:
    needs: build
    name: Generate build provenance
    runs-on: ubuntu-20.04
    steps:
      # checkout only required to run local action (defined in this repo)
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Download build artifact
        uses: actions/download-artifact@v2.0.10
        with:
         name: slsa
         path: slsa

      - name: Generate provenance
        # use action in the root directory
        uses: ./
        with:
          artifact_path: slsa/

      - name: Check and Match contents of provenance
        run: .github/bin/test_provenance.sh build.provenance .github/test_resource/example_build.provenance
